ENHANCED: Improved support for RDF import/output formats.
The following improvements are made:

  - HDT files can now be created based on TriG input.

  - HDT files can now be exported in the TriG format.

  - Command-line tools now correctly advertize all and only supported
    formats.

Implementation details:

  - `RDFNotation::TRIG' was added.

  - `RDFNotation::NQUADS' was added.  The old `RDFNotation::NQUAD' is
    left in place, and is marked deprecated.

The support for RDF serialization formats contained many bugs:

  - It was not possible to generate/export HDTs from/to TriG files,
    even though Serd parses/generates TriG.

  - Serialization formats `n3' and `rdfxml' were still advertized in
    command-line tools, even though using these results in an error:

        $ ./rdf2hdt -f n3 example.ttl example.hdt
        Catch exception load: Item not found
        ERROR: Item not found

  - The Windows-based command-line utility (`rdf2hdt/rdf2hdt.cpp') did
    not support the abbreviation formats (`nq', `nt', and `ttl').

For consistency, the Git ignore file is updated to exclude N-Quads,
TriG, and Turtle files in addition to N-Triples files.

Backwards compatibility is ensured by leaving all old `RDFNotation'
items in place (with the same iteger value).  This includes formats
that are not supported, i.e., `N3', `JSON', and `XML'.